### ISSUE TITLE
Presentations do not seems to be working in orchid 0.21.0 due to javascript error in Editorial theme.

### ISSUE THREAD

**Issue by SnakeSVx** [JavaEden/Orchid#392]
I've been trying out presentations and when I try to open the page I get an error that $.deck is not a function.

`
initDeck.js:2 Uncaught TypeError: $.deck is not a function
    at HTMLDocument.<anonymous> (initDeck.js:2)
    at j (jquery.js:3148)
    at Object.fireWith [as resolveWith] (jquery.js:3260)
    at Function.ready (jquery.js:3472)
    at HTMLDocument.J (jquery.js:3503)
`

I noticed that multiple jquery versions are getting imported, so maybe there is a conflict somewhere.

`
<script  src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script  src="https://cdnjs.cloudflare.com/ajax/libs/skel/3.0.1/skel.min.js"></script>
<script  src="http://localhost:8080/Editorial/87ae4384/assets/js/editorial_util.js"></script>
<script  src="http://localhost:8080/Editorial/87ae4384/assets/js/editorial_main.js"></script>
<script  src="http://localhost:8080/Editorial/87ae4384/assets/js/editorial_orchidCustomizations.js"></script>
<script  src="http://localhost:8080/assets/vendor/modernizr_custom.js"></script>
<script  src="http://localhost:8080/assets/core/deck_core.js"></script>
<script  src="http://localhost:8080/assets/extensions/menu/deck_menu.js"></script>
<script  src="http://localhost:8080/assets/extensions/goto/deck_goto.js"></script>
<script  src="http://localhost:8080/assets/extensions/status/deck_status.js"></script>
<script  src="http://localhost:8080/assets/extensions/navigation/deck_navigation.js"></script>
<script  src="http://localhost:8080/assets/extensions/scale/deck_scale.js"></script>
<script  src="http://localhost:8080/assets/initDeck.js"></script>
<script  src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.17.1/prism.min.js"></script>
<script  src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.17.1/components/prism-java.min.js"></script>
<script  src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.17.1/components/prism-kotlin.min.js"></script>
<script  src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.17.1/components/prism-yaml.min.js"></script>
<script  src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.17.1/components/prism-markup.min.js"></script>
<script  src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.17.1/components/prism-css.min.js"></script>
<script  src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.17.1/components/prism-scss.min.js"></script>
<script  src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.17.1/components/prism-javascript.min.js"></script>
<script  src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.17.1/components/prism-typescript.min.js"></script>
<script  src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.17.1/components/prism-json.min.js"></script>
<script  src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script  src="https://unpkg.com/lunr/lunr.js"></script>
<script  src="http://localhost:8080/assets/js/orchidSearch.js"></script>
`

**Comment by SnakeSVx** [comment]
Extra note: it works in BsDoc, but it doesn't in Editorial. 

Bsdoc contains jquery 3, while Editorial still contains jquery 1.

This issue also causes the search function to not work.
